name: Java CI with JUnit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java classes
      run: javac -d bin src/com/example/*.java

    - name: Run JUnit tests
      run: java -cp bin org.junit.runner.JUnitCore com.example.CalculatorTest
